# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FritzImageSegmentationDemo' do
  use_frameworks!

  pod 'Fritz', '~> 3.7.0'
  pod 'Fritz/VisionSegmentationModel/People'
end
